### ISSUE TITLE
Wire diameter unit

### ISSUE THREAD

**Issue by christian-cahig** [mpewsey/emf#4]
What unit does the `diameter` argument (in initializing `Phase2D`) assume?

https://github.com/mpewsey/emf/blob/cbbda17c9c365f09e4470ea8836c22cd1b0b7dcf/emf/analysis2d/phase2d.py#L19-L20

**Comment by mpewsey** [comment]
> What unit does the `diameter` argument (in initializing `Phase2D`) assume?
> 
> 
> 
> https://github.com/mpewsey/emf/blob/cbbda17c9c365f09e4470ea8836c22cd1b0b7dcf/emf/analysis2d/phase2d.py#L19-L20

The inputs are all in standard SI units (kg, m, s, V, A) since those units all work together without the need for intermediate conversions. So the input diameter should be in meters.

**Comment by christian-cahig** [comment]
> The inputs are all in standard SI units (kg, m, s, V, A) since those units all work together without the need for intermediate conversions. So the input diameter should be in meters.

Thanks! I'm closing this issue now. Great work by the way.
